sudo: required

dist: trusty

language: cpp

services: 
  - mysql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

compiler: gcc

install:
  - mysql -u root -e 'create database Halite;'

  - cd ~/build/HaliteChallenge/Halite/tests
  - cp travisTests.ini tests.ini
  - cp travisTests.ini ../halite.ini
 
  - cd ~/build/HaliteChallenge/Halite/website
  - sudo ./install.sh

  - cd ~/build/HaliteChallenge/Halite/worker
  - sudo ./install.sh

  - cd ~/build/HaliteChallenge/Halite/tests
  - sudo ./install.sh

script:
  - cd ~/build/HaliteChallenge/Halite/tests/
  - sudo ./runTests.sh

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
