# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Halite AI Challenge
email: halite@halite.io
description: > # this means to ignore newlines until "baseurl:"
  Halite is an artificial intelligence programming challenge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://35.185.45.87/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: haliteAI
github_username:  jekyll

permalink: /blog/:year/:month/:day/:title.html

api_server_url: "http://35.190.3.178/v1/api"
login_server_url: "http://35.190.3.178/v1/login"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-toc
sass:
  load_paths:
    - _sass
    - vendor_assets
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - vendor_assets/
  - javascript/
  - node_modules/
